name: Build and Package Tweak

on:
  push:
    branches:
      - main  # Change this to your main branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Theos
      run: |
        git clone https://github.com/theos/theos.git $HOME/theos
        echo "export THEOS=$HOME/theos" >> $GITHUB_ENV
        echo "export PATH=$HOME/theos/bin:$PATH" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ldid dpkg fakeroot gnu-tar

    - name: Build tweak
      run: make package

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: cpuinfooverlay-package
        path: ./packages/*.deb
